# Generated by Django 6.0 on 2026-02-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('scan_type', models.CharField(choices=[('passive', 'Scan Passif'), ('active', 'Scan Actif'), ('both', 'Passif + Actif')], default='both', max_length=20)),
                ('alert_level', models.CharField(choices=[('HIGH', 'Élevé'), ('MEDIUM', 'Moyen'), ('LOW', 'Faible'), ('INFO', 'Info')], default='LOW', max_length=10)),
                ('scan_policy', models.CharField(default='default', max_length=50)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('total_alerts', models.IntegerField(default=0)),
                ('urls_scanned', models.IntegerField(default=0)),
                ('scan_duration', models.FloatField(default=0.0, help_text='Durée du scan en secondes')),
                ('html_report', models.TextField(blank=True)),
                ('report_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Résultat Scan ZAP',
                'verbose_name_plural': 'Résultats Scans ZAP',
                'ordering': ['-created_at'],
            },
        ),
    ]
