# Generated by Django 6.0 on 2026-02-24 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('scans_count', models.IntegerField(default=0)),
                ('vulnerabilities_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Daily Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DashboardStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scans', models.IntegerField(default=0)),
                ('total_vulnerabilities', models.IntegerField(default=0)),
                ('critical_alerts', models.IntegerField(default=0)),
                ('tools_accessed', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Stats',
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('whois', 'WHOIS'), ('dns', 'DNS Lookup'), ('zap', 'OWASP ZAP'), ('checker', 'Username/Email Check'), ('subdomain', 'Subdomain Enum')], max_length=20)),
                ('target', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Complété'), ('failed', 'Erreur')], default='pending', max_length=20)),
                ('vulnerabilities_found', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0, help_text='Durée en secondes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(choices=[('whois', 'WHOIS & DNS Recon'), ('checker', 'Username/Email Check'), ('dns_tool', 'DNS Tool'), ('scanner', 'OWASP ZAP'), ('intruder', 'Burp Suite'), ('perforNet', 'Speed Test')], max_length=50, unique=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tool Usage',
            },
        ),
        migrations.CreateModel(
            name='ScanAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'CRITIQUE'), ('high', 'ÉLEVÉE'), ('medium', 'MOYENNE'), ('low', 'BASSE')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cve', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.scanhistory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
