# Generated by Django 6.0.1 on 2026-02-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyMetrics',
        ),
        migrations.DeleteModel(
            name='DashboardStat',
        ),
        migrations.RemoveField(
            model_name='scanalert',
            name='scan',
        ),
        migrations.DeleteModel(
            name='ToolUsage',
        ),
        migrations.DeleteModel(
            name='ScanAlert',
        ),
        migrations.DeleteModel(
            name='ScanHistory',
        ),
    ]
