# Generated by Django 5.1 on 2026-05-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.URLField(help_text='URL ou IP à scanner (ex: http://192.168.1.1)', max_length=500, verbose_name='URL cible')),
                ('success', models.BooleanField(default=False, verbose_name='Succès')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('raw_output', models.TextField(blank=True, null=True, verbose_name='Sortie brute Nikto')),
                ('findings_json', models.TextField(blank=True, null=True, verbose_name='Findings JSON')),
                ('findings_count', models.IntegerField(default=0, verbose_name='Nombre de vulnérabilités')),
                ('tuning', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tuning Nikto')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='Port')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Démarré le')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
