# Generated by Django 6.0.1 on 2026-04-28 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisecuritytest',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apisecuritytest',
            name='issues_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apisecuritytest',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apisecuritytest',
            name='test_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cvelookup',
            name='affected_versions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cvelookup',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='integrationresult',
            name='critical_issues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='integrationresult',
            name='nuclei_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.nucleiscan'),
        ),
        migrations.AddField(
            model_name='integrationresult',
            name='port_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.portscan'),
        ),
        migrations.AddField(
            model_name='integrationresult',
            name='ssl_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.ssltlscert'),
        ),
        migrations.AddField(
            model_name='nucleiscan',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nucleiscan',
            name='high_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nucleiscan',
            name='info_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nucleiscan',
            name='low_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nucleiscan',
            name='medium_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nucleiscan',
            name='results_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='nucleiscan',
            name='templates_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portscan',
            name='closed_ports_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portscan',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portscan',
            name='filtered_ports_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portscan',
            name='os_detection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portscan',
            name='ports_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ssltlscert',
            name='cipher_suites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ssltlscert',
            name='not_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ssltlscert',
            name='not_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ssltlscert',
            name='security_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ssltlscert',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ssltlscert',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checking', 'Checking'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ssltlscert',
            name='tls_versions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ssltlscert',
            name='vulnerable_ciphers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='apisecuritytest',
            name='test_type',
            field=models.CharField(choices=[('auth', 'Authentication'), ('injection', 'Injection'), ('xss', 'Cross-Site Scripting'), ('cors', 'CORS'), ('rate_limit', 'Rate Limiting'), ('headers', 'Security Headers'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ssltlscert',
            name='subject_alt_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
