# Generated by Django 6.0 on 2026-02-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WHOISResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('domain_info', models.JSONField()),
                ('raw_whois', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'WHOIS Results',
                'ordering': ['-updated_at'],
            },
        ),
    ]
