# Generated by Django 6.0 on 2026-02-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protegioTools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoisresult',
            name='country_from_tld',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
