# Generated by Django 6.0.1 on 2026-02-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protegioTools', '0002_whoisresult_country_from_tld'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WHOISResult',
        ),
    ]
