# Generated by Django 6.0 on 2026-02-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_speed', models.FloatField(help_text='Vitesse de téléchargement en Mbps')),
                ('upload_speed', models.FloatField(help_text='Vitesse de téléchargement inversé en Mbps')),
                ('ping', models.FloatField(help_text='Latence (ping) en ms')),
                ('server_name', models.CharField(help_text='Nom du serveur de test', max_length=255)),
                ('server_country', models.CharField(help_text='Pays du serveur', max_length=100)),
                ('server_city', models.CharField(blank=True, help_text='Ville du serveur', max_length=100)),
                ('isp', models.CharField(help_text="Fournisseur d'accès internet", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Résultat Test Vitesse',
                'verbose_name_plural': 'Résultats Tests Vitesse',
                'ordering': ['-created_at'],
            },
        ),
    ]
